# Generated by Django 5.1.3 on 2025-01-02 08:11

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_driver_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('username',)},
        ),
        migrations.AlterModelManagers(
            name='driver',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
